# Site settings
description: A blog about security stuff I find intresting
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dejandayoff.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dejan Zelic
user_description: Penetration Tester
user_title: Penetration Tester
email: dejanzelic@gmail.com
twitter_username: dejandayoff
github_username:  dejanzelic
gplus_username:  DejanZelicDayoff
disqus_username: dejanzelic
disqus_sitename: dejandayoff

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules','initpost.sh']
